# read metering file

In [43]:
import pandas as pd
import numpy as np
import hashlib, json
import json

In [2]:
def create_dict_measurement(df, date):
    transaction = [{key: value} for key, value in zip(list(df['Account']), list(df['Kwh_total']))]
    return {"date":date, "metering":transaction}

In [3]:
df_metering_all = pd.read_csv('Data/Measurement/meter_n3_000.csv', engine='python')

In [5]:
df_metering_all.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2018,3,20006639758,6008616988,6631098,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,543.0,0000,NaN,WIR04,WIR04,15.474888,101.083673,NaN,NaN,NaN
1,2018,3,20006548900,6008617009,16743173,1115,PPS1,C07201,CWCB0031,1367XF000004715,...,20.0,0000,NaN,WIR01,WIR01,15.691985,101.271455,NaN,NaN,NaN
2,2018,3,20006639954,6008617030,5800764612,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,525.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
3,2018,3,20006639963,6008617039,14541534,2125,PPS1,C07401,CSTP0040,1367XF000003983,...,267.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
4,2018,3,20006686181,6008617069,19041220,1125,PPS1,C07301,CBSP0036,1367XF000005098,...,1144.0,0000,NaN,BSH05,BSH05,15.849482,101.041451,NaN,NaN,NaN

In [74]:
df_temp=df_metering_all.drop(list(np.where(df_metering_all['Year']!=2018)[0])).copy()
df_temp=df_temp.reset_index(drop=True)

In [75]:
df_temp.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2018,3,20006639758,6008616988,6631098,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,543.0,0000,NaN,WIR04,WIR04,15.474888,101.083673,NaN,NaN,NaN
1,2018,3,20006548900,6008617009,16743173,1115,PPS1,C07201,CWCB0031,1367XF000004715,...,20.0,0000,NaN,WIR01,WIR01,15.691985,101.271455,NaN,NaN,NaN
2,2018,3,20006639954,6008617030,5800764612,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,525.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
3,2018,3,20006639963,6008617039,14541534,2125,PPS1,C07401,CSTP0040,1367XF000003983,...,267.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
4,2018,3,20006686181,6008617069,19041220,1125,PPS1,C07301,CBSP0036,1367XF000005098,...,1144.0,0000,NaN,BSH05,BSH05,15.849482,101.041451,NaN,NaN,NaN

In [80]:
#retieve kWhr

In [42]:
temp_dict={}

for Year in [2016, 2017, 2018, 2019]:
    print(Year)
    for file_name in ['meter_n3.{0:03}.csv'.format(i) for i in range(0,75)]:
        print('number of customer {}'.format(len(temp_dict)))
        print(file_name)
        df_metering = pd.read_csv('Data/Measurement/{}'.format(file_name), engine='python')
        df_temp=df_metering.drop(list(np.where(df_metering['Year']!=Year)[0])).copy()
        df_temp=df_temp.reset_index(drop=True)
        for key1, key2, key3, value in zip(list(df_temp['Account']),list(df_temp['Year']),list(df_temp['Month']),list(df_temp['Kwh_total'])):
            if key1 in temp_dict.keys():
                if key2 in temp_dict[key1]:
                    if key3 in temp_dict[key1][key2]:
                        pass
                    else:
                        temp_dict[key1][key2].update({key3:value})
                else:
                    temp_dict[key1].update({key2:{key3:value}})
            else:
                temp_dict.update({key1:{key2:{key3:value}}})

2016
number of customer 0
meter_n3.000.csv
number of customer 169628
meter_n3.001.csv
number of customer 334513
meter_n3.002.csv
number of customer 466894
meter_n3.003.csv
number of customer 588531
meter_n3.004.csv
number of customer 702333
meter_n3.005.csv
number of customer 807803
meter_n3.006.csv
number of customer 874902
meter_n3.007.csv
number of customer 911478
meter_n3.008.csv
number of customer 944941
meter_n3.009.csv
number of customer 976658
meter_n3.010.csv
number of customer 1001090
meter_n3.011.csv
number of customer 1028704
meter_n3.012.csv
number of customer 1053620
meter_n3.013.csv
number of customer 1073890
meter_n3.014.csv
number of customer 1086566
meter_n3.015.csv
number of customer 1100286
meter_n3.016.csv
number of customer 1114899
meter_n3.017.csv
number of customer 1131652
meter_n3.018.csv
number of customer 1146006
meter_n3.019.csv
number of customer 1155058
meter_n3.020.csv
number of customer 1159913
meter_n3.021.csv
number of customer 1163002
meter_n3.022.csv
number of customer 1164688
meter_n3.023.csv
number of customer 1165822
meter_n3.024.csv
number of customer 1166852
meter_n3.025.csv
number of customer 1167573
meter_n3.026.csv
number of customer 1168500
meter_n3.027.csv
number of customer 1169679
meter_n3.028.csv
number of customer 1170711
meter_n3.029.csv
number of customer 1171410
meter_n3.030.csv
number of customer 1172165
meter_n3.031.csv
number of customer 1172615
meter_n3.032.csv
number of customer 1172970
meter_n3.033.csv
number of customer 1173417
meter_n3.034.csv
number of customer 1174018
meter_n3.035.csv
number of customer 1174402
meter_n3.036.csv
number of customer 1175021
meter_n3.037.csv
number of customer 1175469
meter_n3.038.csv
number of customer 1175790
meter_n3.039.csv
number of customer 1176041
meter_n3.040.csv
number of customer 1176127
meter_n3.041.csv
number of customer 1176327
meter_n3.042.csv
number of customer 1176628
meter_n3.043.csv
number of customer 1176951
meter_n3.044.csv
number of customer 1177535
meter_n3.045.csv
number of customer 1178317
meter_n3.046.csv
number of customer 1178949
meter_n3.047.csv
number of customer 1179567
meter_n3.048.csv
number of customer 1180324
meter_n3.049.csv
number of customer 1180363
meter_n3.050.csv
number of customer 1180454
meter_n3.051.csv
number of customer 1180633
meter_n3.052.csv
number of customer 1180898
meter_n3.053.csv
number of customer 1181067
meter_n3.054.csv
number of customer 1181247
meter_n3.055.csv
number of customer 1181452
meter_n3.056.csv
number of customer 1181550
meter_n3.057.csv
number of customer 1181639
meter_n3.058.csv
number of customer 1181639
meter_n3.059.csv
number of customer 1181639
meter_n3.060.csv
number of customer 1181639
meter_n3.061.csv
number of customer 1181639
meter_n3.062.csv
number of customer 1181639
meter_n3.063.csv
number of customer 1181639
meter_n3.064.csv
number of customer 1181639
meter_n3.065.csv
number of customer 1181639
meter_n3.066.csv
number of customer 1181639
meter_n3.067.csv
number of customer 1181639
meter_n3.068.csv
number of customer 1181639
meter_n3.069.csv
number of customer 1181639
meter_n3.070.csv
number of customer 1181639
meter_n3.071.csv
number of customer 1181639
meter_n3.072.csv
number of customer 1181639
meter_n3.073.csv
number of customer 1181639
meter_n3.074.csv
2017
number of customer 1181639
meter_n3.000.csv
number of customer 1184332
meter_n3.001.csv
number of customer 1186786
meter_n3.002.csv
number of customer 1191845
meter_n3.003.csv
number of customer 1196144
meter_n3.004.csv
number of customer 1198352
meter_n3.005.csv
number of customer 1201126
meter_n3.006.csv
number of customer 1203296
meter_n3.007.csv
number of customer 1205182
meter_n3.008.csv
number of customer 1206872
meter_n3.009.csv
number of customer 1208261
meter_n3.010.csv
number of customer 1209020
meter_n3.011.csv
number of customer 1210430
meter_n3.012.csv
number of customer 1211179
meter_n3.013.csv
number of customer 1212048
meter_n3.014.csv
number of customer 1212848
meter_n3.015.csv
number of customer 1213798
meter_n3.016.csv
number of customer 1214626
meter_n3.017.csv
number of customer 1215138
meter_n3.018.csv
number of customer 1215741
meter_n3.019.csv
number of customer 1216324
meter_n3.020.csv
number of customer 1216934
meter_n3.021.csv
number of customer 1217358
meter_n3.022.csv
number of customer 1217822
meter_n3.023.csv
number of customer 1218383
meter_n3.024.csv
number of customer 1218778
meter_n3.025.csv
number of customer 1219345
meter_n3.026.csv
number of customer 1219886
meter_n3.027.csv
number of customer 1220258
meter_n3.028.csv
number of customer 1220608
meter_n3.029.csv
number of customer 1220888
meter_n3.030.csv
number of customer 1221116
meter_n3.031.csv
number of customer 1221404
meter_n3.032.csv
number of customer 1221720
meter_n3.033.csv
number of customer 1221896
meter_n3.034.csv
number of customer 1222108
meter_n3.035.csv
number of customer 1222301
meter_n3.036.csv
number of customer 1222457
meter_n3.037.csv
number of customer 1222635
meter_n3.038.csv
number of customer 1222850
meter_n3.039.csv
number of customer 1223027
meter_n3.040.csv
number of customer 1223205
meter_n3.041.csv
number of customer 1223412
meter_n3.042.csv
number of customer 1223562
meter_n3.043.csv
number of customer 1223677
meter_n3.044.csv
number of customer 1223775
meter_n3.045.csv
number of customer 1223881
meter_n3.046.csv
number of customer 1223957
meter_n3.047.csv
number of customer 1224058
meter_n3.048.csv
number of customer 1224191
meter_n3.049.csv
number of customer 1224304
meter_n3.050.csv
number of customer 1224419
meter_n3.051.csv
number of customer 1224501
meter_n3.052.csv
number of customer 1224579
meter_n3.053.csv
number of customer 1224688
meter_n3.054.csv
number of customer 1224735
meter_n3.055.csv
number of customer 1224835
meter_n3.056.csv
number of customer 1224921
meter_n3.057.csv
number of customer 1224964
meter_n3.058.csv
number of customer 1224995
meter_n3.059.csv
number of customer 1224996
meter_n3.060.csv
number of customer 1224996
meter_n3.061.csv
number of customer 1224996
meter_n3.062.csv
number of customer 1224996
meter_n3.063.csv
number of customer 1224996
meter_n3.064.csv
number of customer 1224996
meter_n3.065.csv
number of customer 1224996
meter_n3.066.csv
number of customer 1224996
meter_n3.067.csv
number of customer 1224996
meter_n3.068.csv
number of customer 1224996
meter_n3.069.csv
number of customer 1224996
meter_n3.070.csv
number of customer 1224996
meter_n3.071.csv
number of customer 1224996
meter_n3.072.csv
number of customer 1224996
meter_n3.073.csv
number of customer 1224996
meter_n3.074.csv
2018
number of customer 1224996
meter_n3.000.csv
number of customer 1225149
meter_n3.001.csv
number of customer 1225199
meter_n3.002.csv
number of customer 1225284
meter_n3.003.csv
number of customer 1225337
meter_n3.004.csv
number of customer 1225361
meter_n3.005.csv
number of customer 1225434
meter_n3.006.csv
number of customer 1225488
meter_n3.007.csv
number of customer 1225534
meter_n3.008.csv
number of customer 1225592
meter_n3.009.csv
number of customer 1225639
meter_n3.010.csv
number of customer 1225679
meter_n3.011.csv
number of customer 1225704
meter_n3.012.csv
number of customer 1225742
meter_n3.013.csv
number of customer 1225788
meter_n3.014.csv
number of customer 1225804
meter_n3.015.csv
number of customer 1225869
meter_n3.016.csv
number of customer 1225925
meter_n3.017.csv
number of customer 1225989
meter_n3.018.csv
number of customer 1226036
meter_n3.019.csv
number of customer 1226105
meter_n3.020.csv
number of customer 1226196
meter_n3.021.csv
number of customer 1226254
meter_n3.022.csv
number of customer 1226317
meter_n3.023.csv
number of customer 1226415
meter_n3.024.csv
number of customer 1226505
meter_n3.025.csv
number of customer 1226542
meter_n3.026.csv
number of customer 1226646
meter_n3.027.csv
number of customer 1226758
meter_n3.028.csv
number of customer 1226831
meter_n3.029.csv
number of customer 1226900
meter_n3.030.csv
number of customer 1226981
meter_n3.031.csv
number of customer 1227072
meter_n3.032.csv
number of customer 1227126
meter_n3.033.csv
number of customer 1227186
meter_n3.034.csv
number of customer 1227252
meter_n3.035.csv
number of customer 1227335
meter_n3.036.csv

number of customer 1227376
meter_n3.037.csv
number of customer 1227449
meter_n3.038.csv
number of customer 1227531
meter_n3.039.csv
number of customer 1227588
meter_n3.040.csv
number of customer 1227623
meter_n3.041.csv
number of customer 1227720
meter_n3.042.csv
number of customer 1227790
meter_n3.043.csv
number of customer 1227844
meter_n3.044.csv
number of customer 1227941
meter_n3.045.csv
number of customer 1228064
meter_n3.046.csv
number of customer 1228079
meter_n3.047.csv
number of customer 1228145
meter_n3.048.csv
number of customer 1228288
meter_n3.049.csv
number of customer 1228288
meter_n3.050.csv
number of customer 1228324
meter_n3.051.csv
number of customer 1228345
meter_n3.052.csv
number of customer 1228429
meter_n3.053.csv
number of customer 1228462
meter_n3.054.csv
number of customer 1228555
meter_n3.055.csv
number of customer 1228660
meter_n3.056.csv
number of customer 1228675
meter_n3.057.csv
number of customer 1228780
meter_n3.058.csv
number of customer 1229346
meter_n3.059.csv
number of customer 1230812
meter_n3.060.csv
number of customer 1234677
meter_n3.061.csv
number of customer 1237390
meter_n3.062.csv
number of customer 1239926
meter_n3.063.csv
number of customer 1240304
meter_n3.064.csv
number of customer 1248508
meter_n3.065.csv
number of customer 1249068
meter_n3.066.csv
number of customer 1249351
meter_n3.067.csv
number of customer 1259388
meter_n3.068.csv
number of customer 1259576
meter_n3.069.csv
number of customer 1259828
meter_n3.070.csv
number of customer 1259898
meter_n3.071.csv
number of customer 1262557
meter_n3.072.csv
number of customer 1262961
meter_n3.073.csv
number of customer 1263002
meter_n3.074.csv
2019
number of customer 1263086
meter_n3.000.csv
number of customer 1263138
meter_n3.001.csv
number of customer 1263174
meter_n3.002.csv
number of customer 1263203
meter_n3.003.csv
number of customer 1263233
meter_n3.004.csv
number of customer 1263274
meter_n3.005.csv
number of customer 1263300
meter_n3.006.csv
number of customer 1263328
meter_n3.007.csv
number of customer 1263362
meter_n3.008.csv
number of customer 1263401
meter_n3.009.csv
number of customer 1263420
meter_n3.010.csv
number of customer 1263456
meter_n3.011.csv
number of customer 1263480
meter_n3.012.csv
number of customer 1263501
meter_n3.013.csv
number of customer 1263526
meter_n3.014.csv
number of customer 1263555
meter_n3.015.csv
number of customer 1263594
meter_n3.016.csv
number of customer 1263621
meter_n3.017.csv
number of customer 1263649
meter_n3.018.csv
number of customer 1263680
meter_n3.019.csv
number of customer 1263711
meter_n3.020.csv
number of customer 1263734
meter_n3.021.csv
number of customer 1263756
meter_n3.022.csv
number of customer 1263776
meter_n3.023.csv
number of customer 1263790
meter_n3.024.csv
number of customer 1263818
meter_n3.025.csv
number of customer 1263847
meter_n3.026.csv
number of customer 1263881
meter_n3.027.csv
number of customer 1263900
meter_n3.028.csv
number of customer 1263926
meter_n3.029.csv
number of customer 1263960
meter_n3.030.csv
number of customer 1263984
meter_n3.031.csv
number of customer 1264018
meter_n3.032.csv
number of customer 1264054
meter_n3.033.csv
number of customer 1264088
meter_n3.034.csv
number of customer 1264125
meter_n3.035.csv
number of customer 1264158
meter_n3.036.csv
number of customer 1264201
meter_n3.037.csv
number of customer 1264238
meter_n3.038.csv
number of customer 1264270
meter_n3.039.csv
number of customer 1264302
meter_n3.040.csv
number of customer 1264321
meter_n3.041.csv
number of customer 1264341
meter_n3.042.csv
number of customer 1264362
meter_n3.043.csv
number of customer 1264392
meter_n3.044.csv
number of customer 1264407
meter_n3.045.csv
number of customer 1264428
meter_n3.046.csv
number of customer 1264468
meter_n3.047.csv
number of customer 1264479
meter_n3.048.csv
number of customer 1264499
meter_n3.049.csv
number of customer 1264520
meter_n3.050.csv
number of customer 1264563
meter_n3.051.csv
number of customer 1264593
meter_n3.052.csv
number of customer 1264617
meter_n3.053.csv
number of customer 1264647
meter_n3.054.csv
number of customer 1264699
meter_n3.055.csv
number of customer 1264749
meter_n3.056.csv
number of customer 1264791
meter_n3.057.csv
number of customer 1264872
meter_n3.058.csv
number of customer 1266788
meter_n3.059.csv
number of customer 1266795
meter_n3.060.csv
number of customer 1267814
meter_n3.061.csv
number of customer 1267818
meter_n3.062.csv
number of customer 1267819
meter_n3.063.csv
number of customer 1267819
meter_n3.064.csv
number of customer 1267846
meter_n3.065.csv
number of customer 1268276
meter_n3.066.csv
number of customer 1268323
meter_n3.067.csv
number of customer 1268325
meter_n3.068.csv
number of customer 1268325
meter_n3.069.csv
number of customer 1268325
meter_n3.070.csv
number of customer 1270016
meter_n3.071.csv
number of customer 1270668
meter_n3.072.csv
number of customer 1270967
meter_n3.073.csv
number of customer 1273672
meter_n3.074.csv

In [44]:
json = json.dumps(temp_dict)
f = open("temp_dict_kWhr.json","w")
f.write(json)
f.close()

In [20]:
df_metering_all = pd.read_csv('Data/Measurement/meter_n3.000.csv', engine='python')

In [21]:
df_metering_all.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2018,3,20006639758,6008616988,6631098,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,543.0,0000,NaN,WIR04,WIR04,15.474888,101.083673,NaN,NaN,NaN
1,2018,3,20006548900,6008617009,16743173,1115,PPS1,C07201,CWCB0031,1367XF000004715,...,20.0,0000,NaN,WIR01,WIR01,15.691985,101.271455,NaN,NaN,NaN
2,2018,3,20006639954,6008617030,5800764612,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,525.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
3,2018,3,20006639963,6008617039,14541534,2125,PPS1,C07401,CSTP0040,1367XF000003983,...,267.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
4,2018,3,20006686181,6008617069,19041220,1125,PPS1,C07301,CBSP0036,1367XF000005098,...,1144.0,0000,NaN,BSH05,BSH05,15.849482,101.041451,NaN,NaN,NaN

In [22]:
list(df_metering_all)

['Year',
 'Month',
 'Account',
 'Installation',
 'Device_no',
 'Rate_cat',
 'Customer_type',
 'PEA_CODE',
 'Mru',
 'Trf_tag',
 'Trf_tag_Dummy',
 'Curr_read',
 'Prev_read',
 'Kwh_total',
 'Note_read',
 'Note_Average',
 'Feeder_ID',
 'Feeder_ID_Dummy',
 'LATITUDE',
 'LONGITUDE',
 'GIS_LATITUDE',
 'GIS_LONGITUDE',
 'Phase']

In [5]:
set(df_metering_all['Note_read'])

{'    ',
 '----',
 '0000',
 '0600',
 '0700',
 '0900',
 '1000',
 '1100',
 '4400',
 '7700',
 '8800',
 nan}

In [23]:
df_temp=df_metering_all.drop(list(np.where(df_metering_all['Note_read']!="1100")[0])).copy()
df_temp=df_temp.reset_index(drop=True)

In [24]:
df_temp.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2019,1,20019472293,6019149561,5700853738,1115,PPS1,C05401,CPBR0030,1317XF000000230,...,0.0,1100,NaN,PRI06,PRI06,14.801832,100.438342,14.801902,100.438365,A
1,2018,4,20006817452,6008598498,B462455,1115,PPS1,C13101,CCBD0107,13XFCA000005895,...,72.0,1100,NaN,CDA03,CDA03,15.324700,101.189804,NaN,NaN,NaN
2,2017,4,20006061995,6008569054,27580994,1115,SM,C02101,CNSW0120,CNSW0120,...,318.0,1100,NaN,C02101,C02101,15.766417,100.141484,NaN,NaN,NaN

In [29]:
#retieve fraude code
temp_dict={}
num_fraud=0
for file_name in ['meter_n3.{0:03}.csv'.format(i) for i in range(0,75)]:
#     print('number of customer {}'.format(len(temp_dict)))
    print(file_name)
    df_metering = pd.read_csv('Data/Measurement/{}'.format(file_name), engine='python')
    df_temp=df_metering.drop(list(np.where(df_metering['Note_read']!="1100")[0])).copy()
#     print(df_temp)
    df_temp=df_temp.reset_index(drop=True)
    print("number of fraud detection " + str(len(df_temp['Note_read'])))
    num_fraud=num_fraud+len(df_temp['Note_read'])
    print("total number of fraude " + str(num_fraud))

    for key1, key2, key3, value1, value2, value3, value4 in zip(
        list(df_temp['Account']),
        list(df_temp['Year']),
        list(df_temp['Month']),
        list(df_temp['Note_read']),
        list(df_temp['Feeder_ID']), 
        list(df_temp['LATITUDE']), 
        list(df_temp['LONGITUDE'])):
        
        if key1 in temp_dict.keys():
            if key2 in temp_dict[key1]:
                if key3 in temp_dict[key1][key2]:
                    pass
                else:
                    temp_dict[key1][key2].update({key3:{'Note_read': value1, 'Feeder_ID':value2, 'LATITUDE':value3, 'LONGITUDE': value4}})
            else:
                temp_dict[key1].update({key2:{key3:{'Note_read': value1, 'Feeder_ID':value2, 'LATITUDE':value3, 'LONGITUDE': value4}}})
        else:
            temp_dict.update({key1:{key2:{key3:{'Note_read': value1, 'Feeder_ID':value2, 'LATITUDE':value3, 'LONGITUDE': value4}}}})
#     print(temp_dict)
json = json.dumps(temp_dict)
f = open("temp_dict_fraud_detect.json","w")
f.write(json)
f.close()

meter_n3.000.csv
number of fraud detection 3
total number of fraude 3
meter_n3.001.csv
number of fraud detection 1
total number of fraude 4
meter_n3.002.csv
number of fraud detection 1
total number of fraude 5
meter_n3.003.csv
number of fraud detection 4
total number of fraude 9
meter_n3.004.csv
number of fraud detection 2
total number of fraude 11
meter_n3.005.csv
number of fraud detection 4
total number of fraude 15
meter_n3.006.csv
number of fraud detection 2
total number of fraude 17
meter_n3.007.csv
number of fraud detection 1
total number of fraude 18
meter_n3.008.csv
number of fraud detection 1
total number of fraude 19
meter_n3.009.csv
number of fraud detection 0
total number of fraude 19
meter_n3.010.csv
number of fraud detection 2
total number of fraude 21
meter_n3.011.csv
number of fraud detection 2
total number of fraude 23
meter_n3.012.csv
number of fraud detection 2
total number of fraude 25
meter_n3.013.csv
number of fraud detection 1
total number of fraude 26
meter_n3.014.csv
number of fraud detection 1
total number of fraude 27
meter_n3.015.csv
number of fraud detection 0
total number of fraude 27
meter_n3.016.csv
number of fraud detection 2
total number of fraude 29
meter_n3.017.csv
number of fraud detection 3
total number of fraude 32
meter_n3.018.csv
number of fraud detection 6
total number of fraude 38
meter_n3.019.csv
number of fraud detection 4
total number of fraude 42
meter_n3.020.csv
number of fraud detection 4
total number of fraude 46
meter_n3.021.csv
number of fraud detection 7
total number of fraude 53
meter_n3.022.csv
number of fraud detection 1
total number of fraude 54
meter_n3.023.csv
number of fraud detection 3
total number of fraude 57
meter_n3.024.csv
number of fraud detection 1
total number of fraude 58
meter_n3.025.csv
number of fraud detection 3
total number of fraude 61
meter_n3.026.csv
number of fraud detection 2
total number of fraude 63
meter_n3.027.csv
number of fraud detection 4
total number of fraude 67
meter_n3.028.csv
number of fraud detection 1
total number of fraude 68
meter_n3.029.csv
number of fraud detection 1
total number of fraude 69
meter_n3.030.csv
number of fraud detection 1
total number of fraude 70
meter_n3.031.csv
number of fraud detection 6
total number of fraude 76
meter_n3.032.csv
number of fraud detection 5
total number of fraude 81
meter_n3.033.csv
number of fraud detection 1
total number of fraude 82
meter_n3.034.csv
number of fraud detection 3
total number of fraude 85
meter_n3.035.csv
number of fraud detection 1
total number of fraude 86
meter_n3.036.csv
number of fraud detection 3
total number of fraude 89
meter_n3.037.csv
number of fraud detection 2
total number of fraude 91
meter_n3.038.csv
number of fraud detection 5
total number of fraude 96
meter_n3.039.csv
number of fraud detection 1
total number of fraude 97
meter_n3.040.csv
number of fraud detection 3
total number of fraude 100
meter_n3.041.csv
number of fraud detection 2
total number of fraude 102
meter_n3.042.csv
number of fraud detection 1
total number of fraude 103
meter_n3.043.csv
number of fraud detection 4
total number of fraude 107
meter_n3.044.csv
number of fraud detection 4
total number of fraude 111
meter_n3.045.csv
number of fraud detection 0
total number of fraude 111
meter_n3.046.csv
number of fraud detection 4
total number of fraude 115
meter_n3.047.csv
number of fraud detection 2
total number of fraude 117
meter_n3.048.csv
number of fraud detection 2
total number of fraude 119
meter_n3.049.csv
number of fraud detection 2
total number of fraude 121
meter_n3.050.csv
number of fraud detection 4
total number of fraude 125
meter_n3.051.csv
number of fraud detection 0
total number of fraude 125
meter_n3.052.csv
number of fraud detection 2
total number of fraude 127
meter_n3.053.csv
number of fraud detection 4
total number of fraude 131
meter_n3.054.csv
number of fraud detection 4
total number of fraude 135
meter_n3.055.csv
number of fraud detection 2
total number of fraude 137
meter_n3.056.csv
number of fraud detection 1
total number of fraude 138
meter_n3.057.csv
number of fraud detection 3
total number of fraude 141
meter_n3.058.csv
number of fraud detection 6
total number of fraude 147
meter_n3.059.csv
number of fraud detection 6
total number of fraude 153
meter_n3.060.csv
number of fraud detection 11
total number of fraude 164
meter_n3.061.csv
number of fraud detection 8
total number of fraude 172
meter_n3.062.csv
number of fraud detection 2
total number of fraude 174
meter_n3.063.csv
number of fraud detection 6
total number of fraude 180
meter_n3.064.csv
number of fraud detection 1
total number of fraude 181
meter_n3.065.csv
number of fraud detection 4
total number of fraude 185
meter_n3.066.csv
number of fraud detection 8
total number of fraude 193
meter_n3.067.csv
number of fraud detection 3
total number of fraude 196
meter_n3.068.csv
number of fraud detection 8
total number of fraude 204
meter_n3.069.csv
number of fraud detection 6
total number of fraude 210
meter_n3.070.csv
number of fraud detection 6
total number of fraude 216
meter_n3.071.csv
number of fraud detection 6
total number of fraude 222
meter_n3.072.csv
number of fraud detection 4
total number of fraude 226
meter_n3.073.csv
number of fraud detection 11
total number of fraude 237
meter_n3.074.csv
number of fraud detection 6
total number of fraude 243

In [36]:
temp_dict[20019472293][2019][1]['Feeder_ID']

'PRI06'

In [ ]:
# temp_dict={'dummy_pea_no':{'dummy_year': {'dummpy_month': 100000}}}
temp_dict={}

for key1, key2, key3, value in zip(list(test_df['PEA_no']),list(test_df['Year']),list(test_df['Month']),list(test_df['KwHr'])):
    if key1 in temp_dict.keys():
        if key2 in temp_dict[key1]:
            if key3 in temp_dict[key1][key2]:
                pass
            else:
                temp_dict[key1][key2].update({key3:value})
        else:
            temp_dict[key1].update({key2:{key3:value}})
    else:
        temp_dict.update({key1:{key2:{key3:value}}})

# hashing data

In [ ]:
def create_transactions(df_metering, previous_hash):
    transaction = [{key: value} for key, value in zip(list(df_metering['Account']), list(df_metering['Kwh_total']))]
    return {"prev_hash": previous_hash, "transactions":transaction}

block_genesis=create_transactions(df_metering, 'None')
print(block_genesis_hash)

https://stackoverflow.com/questions/3006710/python-unhash-value

https://medium.com/coinmonks/building-a-simple-blockchain-data-structure-with-python-e7ebd448647a