# read metering file

In [2]:
import pandas as pd
import numpy as np
import hashlib, json
import json

In [2]:
def create_dict_measurement(df, date):
    transaction = [{key: value} for key, value in zip(list(df['Account']), list(df['Kwh_total']))]
    return {"date":date, "metering":transaction}

In [3]:
df_metering_all = pd.read_csv('Data/Measurement/meter_n3_000.csv', engine='python')

In [5]:
df_metering_all.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2018,3,20006639758,6008616988,6631098,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,543.0,0000,NaN,WIR04,WIR04,15.474888,101.083673,NaN,NaN,NaN
1,2018,3,20006548900,6008617009,16743173,1115,PPS1,C07201,CWCB0031,1367XF000004715,...,20.0,0000,NaN,WIR01,WIR01,15.691985,101.271455,NaN,NaN,NaN
2,2018,3,20006639954,6008617030,5800764612,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,525.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
3,2018,3,20006639963,6008617039,14541534,2125,PPS1,C07401,CSTP0040,1367XF000003983,...,267.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
4,2018,3,20006686181,6008617069,19041220,1125,PPS1,C07301,CBSP0036,1367XF000005098,...,1144.0,0000,NaN,BSH05,BSH05,15.849482,101.041451,NaN,NaN,NaN

In [74]:
df_temp=df_metering_all.drop(list(np.where(df_metering_all['Year']!=2018)[0])).copy()
df_temp=df_temp.reset_index(drop=True)

In [75]:
df_temp.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2018,3,20006639758,6008616988,6631098,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,543.0,0000,NaN,WIR04,WIR04,15.474888,101.083673,NaN,NaN,NaN
1,2018,3,20006548900,6008617009,16743173,1115,PPS1,C07201,CWCB0031,1367XF000004715,...,20.0,0000,NaN,WIR01,WIR01,15.691985,101.271455,NaN,NaN,NaN
2,2018,3,20006639954,6008617030,5800764612,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,525.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
3,2018,3,20006639963,6008617039,14541534,2125,PPS1,C07401,CSTP0040,1367XF000003983,...,267.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
4,2018,3,20006686181,6008617069,19041220,1125,PPS1,C07301,CBSP0036,1367XF000005098,...,1144.0,0000,NaN,BSH05,BSH05,15.849482,101.041451,NaN,NaN,NaN

In [80]:
#retieve kWhr

In [93]:
temp_dict={}

for Year in [2016, 2017, 2018, 2019]:
    print(Year)
    for file_name in ['meter_n3.{0:03}.csv'.format(i) for i in range(0,75)]:
        print('number of customer {}'.format(len(temp_dict)))
        print(file_name)
        df_metering = pd.read_csv('Data/Measurement/{}'.format(file_name), engine='python')
        df_temp=df_metering.drop(list(np.where(df_metering['Year']!=Year)[0])).copy()
        df_temp=df_temp.reset_index(drop=True)
        for key1, key2, key3, value in zip(list(df_temp['Account']),list(df_temp['Year']),list(df_temp['Month']),list(df_temp['Kwh_total'])):
            if key1 in temp_dict.keys():
                if key2 in temp_dict[key1]:
                    if key3 in temp_dict[key1][key2]:
                        pass
                    else:
                        temp_dict[key1][key2].update({key3:value})
                else:
                    temp_dict[key1].update({key2:{key3:value}})
            else:
                temp_dict.update({key1:{key2:{key3:value}}})
json = json.dumps(temp_dict)
f = open("temp_dict_kWhr.json","w")
f.write(json)
f.close()

2016
number of customer 0
meter_n3_000.csv
number of customer 169628
meter_n3_001.csv
number of customer 169628
meter_n3_002.csv
number of customer 169628
meter_n3_003.csv
number of customer 169628
meter_n3_004.csv
number of customer 169628
meter_n3_005.csv
number of customer 169628
meter_n3_006.csv
number of customer 169628
meter_n3_007.csv
number of customer 169628
meter_n3_008.csv
number of customer 169628
meter_n3_009.csv
number of customer 169628
meter_n3_010.csv
number of customer 169628
meter_n3_011.csv
number of customer 169628
meter_n3_012.csv
number of customer 169628
meter_n3_013.csv
number of customer 169628
meter_n3_014.csv
number of customer 169628
meter_n3_015.csv
number of customer 169628
meter_n3_016.csv
number of customer 169628
meter_n3_017.csv
number of customer 169628
meter_n3_018.csv
number of customer 169628
meter_n3_019.csv
number of customer 169628
meter_n3_020.csv
number of customer 169628
meter_n3_021.csv
number of customer 169628
meter_n3_022.csv
number of customer 169628
meter_n3_023.csv
number of customer 169628
meter_n3_024.csv
number of customer 169628
meter_n3_025.csv
number of customer 169628
meter_n3_026.csv
number of customer 169628
meter_n3_027.csv
number of customer 169628
meter_n3_028.csv
number of customer 169628
meter_n3_029.csv
number of customer 169628
meter_n3_030.csv
number of customer 169628
meter_n3_031.csv
number of customer 169628
meter_n3_032.csv
number of customer 169628
meter_n3_033.csv
number of customer 169628
meter_n3_034.csv
number of customer 169628
meter_n3_035.csv
number of customer 169628
meter_n3_036.csv
number of customer 169628
meter_n3_037.csv
number of customer 169628
meter_n3_038.csv
number of customer 169628
meter_n3_039.csv
number of customer 169628
meter_n3_040.csv
number of customer 169628
meter_n3_041.csv
number of customer 169628
meter_n3_042.csv
number of customer 169628
meter_n3_043.csv
number of customer 169628
meter_n3_044.csv
number of customer 169628
meter_n3_045.csv
number of customer 169628
meter_n3_046.csv
number of customer 169628
meter_n3_047.csv
number of customer 169628
meter_n3_048.csv
number of customer 169628
meter_n3_049.csv
number of customer 169628
meter_n3_050.csv
number of customer 169628
meter_n3_051.csv
number of customer 169628
meter_n3_052.csv
number of customer 169628
meter_n3_053.csv
number of customer 169628
meter_n3_054.csv
number of customer 169628
meter_n3_055.csv
number of customer 169628
meter_n3_056.csv
number of customer 169628
meter_n3_057.csv
number of customer 169628
meter_n3_058.csv
number of customer 169628
meter_n3_059.csv
number of customer 169628
meter_n3_060.csv
number of customer 169628
meter_n3_061.csv
number of customer 169628
meter_n3_062.csv
number of customer 169628
meter_n3_063.csv
number of customer 169628
meter_n3_064.csv
number of customer 169628
meter_n3_065.csv
number of customer 169628
meter_n3_066.csv
number of customer 169628
meter_n3_067.csv
number of customer 169628
meter_n3_068.csv
number of customer 169628
meter_n3_069.csv
number of customer 169628
meter_n3_070.csv
number of customer 169628
meter_n3_071.csv
number of customer 169628
meter_n3_072.csv
number of customer 169628
meter_n3_073.csv
number of customer 169628
meter_n3_074.csv
2017
number of customer 169628
meter_n3_000.csv
number of customer 345336
meter_n3_001.csv
number of customer 345336
meter_n3_002.csv
number of customer 345336
meter_n3_003.csv
number of customer 345336
meter_n3_004.csv
number of customer 345336
meter_n3_005.csv
number of customer 345336
meter_n3_006.csv
number of customer 345336
meter_n3_007.csv
number of customer 345336
meter_n3_008.csv
number of customer 345336
meter_n3_009.csv
number of customer 345336
meter_n3_010.csv
number of customer 345336
meter_n3_011.csv
number of customer 345336
meter_n3_012.csv
number of customer 345336
meter_n3_013.csv
number of customer 345336
meter_n3_014.csv
number of customer 345336
meter_n3_015.csv
number of customer 345336
meter_n3_016.csv
number of customer 345336
meter_n3_017.csv
number of customer 345336
meter_n3_018.csv
number of customer 345336
meter_n3_019.csv
number of customer 345336
meter_n3_020.csv
number of customer 345336
meter_n3_021.csv
number of customer 345336
meter_n3_022.csv
number of customer 345336
meter_n3_023.csv
number of customer 345336
meter_n3_024.csv
number of customer 345336
meter_n3_025.csv
number of customer 345336
meter_n3_026.csv
number of customer 345336
meter_n3_027.csv
number of customer 345336
meter_n3_028.csv
number of customer 345336
meter_n3_029.csv
number of customer 345336
meter_n3_030.csv
number of customer 345336
meter_n3_031.csv
number of customer 345336
meter_n3_032.csv
number of customer 345336
meter_n3_033.csv
number of customer 345336
meter_n3_034.csv
number of customer 345336
meter_n3_035.csv
number of customer 345336
meter_n3_036.csv
number of customer 345336
meter_n3_037.csv
number of customer 345336
meter_n3_038.csv
number of customer 345336
meter_n3_039.csv
number of customer 345336
meter_n3_040.csv
number of customer 345336
meter_n3_041.csv
number of customer 345336
meter_n3_042.csv
number of customer 345336
meter_n3_043.csv
number of customer 345336
meter_n3_044.csv
number of customer 345336
meter_n3_045.csv
number of customer 345336
meter_n3_046.csv
number of customer 345336
meter_n3_047.csv
number of customer 345336
meter_n3_048.csv
number of customer 345336
meter_n3_049.csv
number of customer 345336
meter_n3_050.csv
number of customer 345336
meter_n3_051.csv
number of customer 345336
meter_n3_052.csv
number of customer 345336
meter_n3_053.csv
number of customer 345336
meter_n3_054.csv
number of customer 345336
meter_n3_055.csv
number of customer 345336
meter_n3_056.csv
number of customer 345336
meter_n3_057.csv
number of customer 345336
meter_n3_058.csv
number of customer 345336
meter_n3_059.csv
number of customer 345336
meter_n3_060.csv
number of customer 345336
meter_n3_061.csv
number of customer 345336
meter_n3_062.csv
number of customer 345336
meter_n3_063.csv
number of customer 345336
meter_n3_064.csv
number of customer 345336
meter_n3_065.csv
number of customer 345336
meter_n3_066.csv
number of customer 345336
meter_n3_067.csv
number of customer 345336
meter_n3_068.csv
number of customer 345336
meter_n3_069.csv
number of customer 345336
meter_n3_070.csv
number of customer 345336
meter_n3_071.csv
number of customer 345336
meter_n3_072.csv
number of customer 345336
meter_n3_073.csv
number of customer 345336
meter_n3_074.csv
2018
number of customer 345336
meter_n3_000.csv
number of customer 429112
meter_n3_001.csv
number of customer 429112
meter_n3_002.csv
number of customer 429112
meter_n3_003.csv
number of customer 429112
meter_n3_004.csv
number of customer 429112
meter_n3_005.csv
number of customer 429112
meter_n3_006.csv
number of customer 429112
meter_n3_007.csv
number of customer 429112
meter_n3_008.csv
number of customer 429112
meter_n3_009.csv
number of customer 429112
meter_n3_010.csv
number of customer 429112
meter_n3_011.csv
number of customer 429112
meter_n3_012.csv
number of customer 429112
meter_n3_013.csv
number of customer 429112
meter_n3_014.csv
number of customer 429112
meter_n3_015.csv
number of customer 429112
meter_n3_016.csv
number of customer 429112
meter_n3_017.csv
number of customer 429112
meter_n3_018.csv
number of customer 429112
meter_n3_019.csv
number of customer 429112
meter_n3_020.csv
number of customer 429112
meter_n3_021.csv
number of customer 429112
meter_n3_022.csv
number of customer 429112
meter_n3_023.csv
number of customer 429112
meter_n3_024.csv
number of customer 429112
meter_n3_025.csv
number of customer 429112
meter_n3_026.csv
number of customer 429112
meter_n3_027.csv
number of customer 429112
meter_n3_028.csv
number of customer 429112
meter_n3_029.csv
number of customer 429112
meter_n3_030.csv
number of customer 429112
meter_n3_031.csv
number of customer 429112
meter_n3_032.csv
number of customer 429112
meter_n3_033.csv
number of customer 429112
meter_n3_034.csv
number of customer 429112
meter_n3_035.csv
number of customer 429112
meter_n3_036.csv
number of customer 429112
meter_n3_037.csv
number of customer 429112
meter_n3_038.csv
number of customer 429112
meter_n3_039.csv
number of customer 429112
meter_n3_040.csv

number of customer 429112
meter_n3_041.csv
number of customer 429112
meter_n3_042.csv
number of customer 429112
meter_n3_043.csv
number of customer 429112
meter_n3_044.csv
number of customer 429112
meter_n3_045.csv
number of customer 429112
meter_n3_046.csv
number of customer 429112
meter_n3_047.csv
number of customer 429112
meter_n3_048.csv
number of customer 429112
meter_n3_049.csv
number of customer 429112
meter_n3_050.csv
number of customer 429112
meter_n3_051.csv
number of customer 429112
meter_n3_052.csv
number of customer 429112
meter_n3_053.csv
number of customer 429112
meter_n3_054.csv
number of customer 429112
meter_n3_055.csv
number of customer 429112
meter_n3_056.csv
number of customer 429112
meter_n3_057.csv
number of customer 429112
meter_n3_058.csv
number of customer 429112
meter_n3_059.csv
number of customer 429112
meter_n3_060.csv
number of customer 429112
meter_n3_061.csv
number of customer 429112
meter_n3_062.csv
number of customer 429112
meter_n3_063.csv
number of customer 429112
meter_n3_064.csv
number of customer 429112
meter_n3_065.csv
number of customer 429112
meter_n3_066.csv
number of customer 429112
meter_n3_067.csv
number of customer 429112
meter_n3_068.csv
number of customer 429112
meter_n3_069.csv
number of customer 429112
meter_n3_070.csv
number of customer 429112
meter_n3_071.csv
number of customer 429112
meter_n3_072.csv
number of customer 429112
meter_n3_073.csv
number of customer 429112
meter_n3_074.csv
2019
number of customer 429112
meter_n3_000.csv
number of customer 440376
meter_n3_001.csv
number of customer 440376
meter_n3_002.csv
number of customer 440376
meter_n3_003.csv
number of customer 440376
meter_n3_004.csv
number of customer 440376
meter_n3_005.csv
number of customer 440376
meter_n3_006.csv
number of customer 440376
meter_n3_007.csv
number of customer 440376
meter_n3_008.csv
number of customer 440376
meter_n3_009.csv
number of customer 440376
meter_n3_010.csv
number of customer 440376
meter_n3_011.csv
number of customer 440376
meter_n3_012.csv
number of customer 440376
meter_n3_013.csv
number of customer 440376
meter_n3_014.csv
number of customer 440376
meter_n3_015.csv
number of customer 440376
meter_n3_016.csv
number of customer 440376
meter_n3_017.csv
number of customer 440376
meter_n3_018.csv
number of customer 440376
meter_n3_019.csv
number of customer 440376
meter_n3_020.csv
number of customer 440376
meter_n3_021.csv
number of customer 440376
meter_n3_022.csv
number of customer 440376
meter_n3_023.csv
number of customer 440376
meter_n3_024.csv
number of customer 440376
meter_n3_025.csv
number of customer 440376
meter_n3_026.csv
number of customer 440376
meter_n3_027.csv
number of customer 440376
meter_n3_028.csv
number of customer 440376
meter_n3_029.csv
number of customer 440376
meter_n3_030.csv
number of customer 440376
meter_n3_031.csv
number of customer 440376
meter_n3_032.csv
number of customer 440376
meter_n3_033.csv
number of customer 440376
meter_n3_034.csv
number of customer 440376
meter_n3_035.csv
number of customer 440376
meter_n3_036.csv
number of customer 440376
meter_n3_037.csv
number of customer 440376
meter_n3_038.csv
number of customer 440376
meter_n3_039.csv
number of customer 440376
meter_n3_040.csv
number of customer 440376
meter_n3_041.csv
number of customer 440376
meter_n3_042.csv
number of customer 440376
meter_n3_043.csv
number of customer 440376
meter_n3_044.csv
number of customer 440376
meter_n3_045.csv
number of customer 440376
meter_n3_046.csv
number of customer 440376
meter_n3_047.csv
number of customer 440376
meter_n3_048.csv
number of customer 440376
meter_n3_049.csv
number of customer 440376
meter_n3_050.csv
number of customer 440376
meter_n3_051.csv
number of customer 440376
meter_n3_052.csv
number of customer 440376
meter_n3_053.csv
number of customer 440376
meter_n3_054.csv
number of customer 440376
meter_n3_055.csv
number of customer 440376
meter_n3_056.csv
number of customer 440376
meter_n3_057.csv
number of customer 440376
meter_n3_058.csv
number of customer 440376
meter_n3_059.csv
number of customer 440376
meter_n3_060.csv
number of customer 440376
meter_n3_061.csv
number of customer 440376
meter_n3_062.csv
number of customer 440376
meter_n3_063.csv
number of customer 440376
meter_n3_064.csv
number of customer 440376
meter_n3_065.csv
number of customer 440376
meter_n3_066.csv
number of customer 440376
meter_n3_067.csv
number of customer 440376
meter_n3_068.csv
number of customer 440376
meter_n3_069.csv
number of customer 440376
meter_n3_070.csv
number of customer 440376
meter_n3_071.csv
number of customer 440376
meter_n3_072.csv
number of customer 440376
meter_n3_073.csv
number of customer 440376
meter_n3_074.csv

In [3]:
df_metering_all = pd.read_csv('Data/Measurement/meter_n3.000.csv', engine='python')

In [4]:
df_metering_all.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2018,3,20006639758,6008616988,6631098,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,543.0,0000,NaN,WIR04,WIR04,15.474888,101.083673,NaN,NaN,NaN
1,2018,3,20006548900,6008617009,16743173,1115,PPS1,C07201,CWCB0031,1367XF000004715,...,20.0,0000,NaN,WIR01,WIR01,15.691985,101.271455,NaN,NaN,NaN
2,2018,3,20006639954,6008617030,5800764612,1125,PPS1,C07401,CSTP0040,1367XF000003983,...,525.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
3,2018,3,20006639963,6008617039,14541534,2125,PPS1,C07401,CSTP0040,1367XF000003983,...,267.0,0000,NaN,WIR04,WIR04,15.474976,101.084447,NaN,NaN,NaN
4,2018,3,20006686181,6008617069,19041220,1125,PPS1,C07301,CBSP0036,1367XF000005098,...,1144.0,0000,NaN,BSH05,BSH05,15.849482,101.041451,NaN,NaN,NaN

In [5]:
set(df_metering_all['Note_read'])

{'    ',
 '----',
 '0000',
 '0600',
 '0700',
 '0900',
 '1000',
 '1100',
 '4400',
 '7700',
 '8800',
 nan}

In [6]:
df_temp=df_metering_all.drop(list(np.where(df_metering_all['Note_read']!="1100")[0])).copy()
df_temp=df_temp.reset_index(drop=True)

In [7]:
df_temp.head()

,Year,Month,Account,Installation,Device_no,Rate_cat,Customer_type,PEA_CODE,Mru,Trf_tag,...,Kwh_total,Note_read,Note_Average,Feeder_ID,Feeder_ID_Dummy,LATITUDE,LONGITUDE,GIS_LATITUDE,GIS_LONGITUDE,Phase
0,2019,1,20019472293,6019149561,5700853738,1115,PPS1,C05401,CPBR0030,1317XF000000230,...,0.0,1100,NaN,PRI06,PRI06,14.801832,100.438342,14.801902,100.438365,A
1,2018,4,20006817452,6008598498,B462455,1115,PPS1,C13101,CCBD0107,13XFCA000005895,...,72.0,1100,NaN,CDA03,CDA03,15.324700,101.189804,NaN,NaN,NaN
2,2017,4,20006061995,6008569054,27580994,1115,SM,C02101,CNSW0120,CNSW0120,...,318.0,1100,NaN,C02101,C02101,15.766417,100.141484,NaN,NaN,NaN

In [19]:
#retieve fraude code
temp_dict={}

for file_name in ['meter_n3.{0:03}.csv'.format(i) for i in range(0,75)]:
    print('number of customer {}'.format(len(temp_dict)))
    print(file_name)
    df_metering = pd.read_csv('Data/Measurement/{}'.format(file_name), engine='python')
    df_temp=df_metering.drop(list(np.where(df_metering['Note_read']!="1100")[0])).copy()
    print(df_temp)
    df_temp=df_temp.reset_index(drop=True)
    print("number of fraud detection" + str(len(df_temp['Note_read'])))
    for key1, key2, key3, value in zip(list(df_temp['Account']),list(df_temp['Year']),list(df_temp['Month']),list(df_temp['Note_read'])):
        if key1 in temp_dict.keys():
            if key2 in temp_dict[key1]:
                if key3 in temp_dict[key1][key2]:
                    pass
                else:
                    temp_dict[key1][key2].update({key3:value})
            else:
                temp_dict[key1].update({key2:{key3:value}})
        else:
            temp_dict.update({key1:{key2:{key3:value}}})
    print(temp_dict)
json = json.dumps(temp_dict)
f = open("temp_dict_fraud_detect.json","w")
f.write(json)
f.close()

number of customer 0
meter_n3.000.csv
        Year  Month      Account  Installation        Device_no Rate_cat  \
2174    2019      1  20019472293    6019149561  5700853738          1115
128288  2018      4  20006817452    6008598498  B462455             1115
941893  2017      4  20006061995    6008569054  27580994            1115

       Customer_type PEA_CODE       Mru          Trf_tag  ...  Kwh_total  \
2174      PPS1         C05401  CPBR0030  1317XF000000230  ...        0.0
128288    PPS1         C13101  CCBD0107  13XFCA000005895  ...       72.0
941893    SM           C02101  CNSW0120         CNSW0120  ...      318.0

        Note_read  Note_Average  Feeder_ID Feeder_ID_Dummy   LATITUDE  \
2174         1100           NaN      PRI06           PRI06  14.801832
128288       1100           NaN      CDA03           CDA03  15.324700
941893       1100           NaN     C02101          C02101  15.766417

         LONGITUDE GIS_LATITUDE  GIS_LONGITUDE  Phase
2174    100.438342    14.801902     100.438365    A
128288  101.189804          NaN            NaN    NaN
941893  100.141484          NaN            NaN    NaN

[3 rows x 23 columns]
number of fraud detection3
{20019472293: {2019: {1: '1100'}}, 20006817452: {2018: {4: '1100'}}, 20006061995: {2017: {4: '1100'}}}
number of customer 3
meter_n3.001.csv

KeyError: 'Note_read'

In [16]:
str(len(df_temp['Note_read']))

'3'

In [ ]:
# temp_dict={'dummy_pea_no':{'dummy_year': {'dummpy_month': 100000}}}
temp_dict={}

for key1, key2, key3, value in zip(list(test_df['PEA_no']),list(test_df['Year']),list(test_df['Month']),list(test_df['KwHr'])):
    if key1 in temp_dict.keys():
        if key2 in temp_dict[key1]:
            if key3 in temp_dict[key1][key2]:
                pass
            else:
                temp_dict[key1][key2].update({key3:value})
        else:
            temp_dict[key1].update({key2:{key3:value}})
    else:
        temp_dict.update({key1:{key2:{key3:value}}})

# hashing data

In [ ]:
def create_transactions(df_metering, previous_hash):
    transaction = [{key: value} for key, value in zip(list(df_metering['Account']), list(df_metering['Kwh_total']))]
    return {"prev_hash": previous_hash, "transactions":transaction}

block_genesis=create_transactions(df_metering, 'None')
print(block_genesis_hash)

https://stackoverflow.com/questions/3006710/python-unhash-value

https://medium.com/coinmonks/building-a-simple-blockchain-data-structure-with-python-e7ebd448647a